export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const ADD_TASK = 'ADD_TASK'
export const CHECKED_TASK = 'CHECKED_TASK'
export const DELETE_TASK = 'DELETE_TASK'

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
